# 项目配置文件

# 数据配置
data:
  input_path: "data/raw/gp_features.parquet"
  output_path: "data/processed/"
  train_end_date: "2022-12-31"
  test_start_date: "2023-01-01"

# 遗传规划参数
genetic_programming:
  population_size: 100
  generations: 50
  tournament_size: 7
  crossover_prob: 0.8
  mutation_prob: 0.1
  max_tree_depth: 4
  hall_of_fame_size: 10

# 因子评估参数
evaluation:
  ic_weight: 0.4
  ir_weight: 0.3
  turnover_penalty_weight: 0.2
  min_stocks_for_evaluation: 50
  evaluation_window: 20
  n_groups: 5
  top_n_for_turnover: 50

# 可视化参数
visualization:
  figure_size: [15, 10]
  dpi: 300
  style: "seaborn"
  color_palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]

# 输出配置
output:
  figures_dir: "outputs/figures/"
  reports_dir: "outputs/reports/"
  models_dir: "outputs/models/"
  log_file: "outputs/factor_mining.log"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"